version: '3.8'

services:
  starlink-monitor:
    build: .
    container_name: starlink-monitor
    network_mode: host
    restart: unless-stopped
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - DATABASE_PATH=/app/data/starlink_data.db
    volumes:
      # Persistent data storage for SQLite database
      - ./data:/app/data
      # Development volumes (for live code updates)
      - ./temp3:/app/temp3:ro
      - ./src:/app/src:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for production use
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: starlink-postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_DB=starlink
  #     - POSTGRES_USER=starlink
  #     - POSTGRES_PASSWORD=your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: